name: dynamo-vllm-local_1

networks:
  server:
    driver: bridge

services:
  dynamo-vllm:
    image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.1
    command: >
      bash -c "
      echo '=== Starting Dynamo frontend ===' &&
      python3 -m dynamo.frontend --http-port 8000 --store-kv file &
      
      echo '=== Waiting for frontend to initialize ===' &&
      sleep 15 &&
      
      echo '=== Starting vLLM backend ===' &&
      python3 -m dynamo.vllm --model Qwen/Qwen3-32B-FP8 --store-kv file --kv-events-config '{\"enable_kv_cache_events\": false}' --gpu-memory-utilization 0.8
      --max-model-len 10000 
      "
    networks:
      - server
    ports:
      - 8000:8000
    ipc: host
    env_file:
      - ../.env
    ulimits:
      memlock: -1
      stack: 67108864
      nofile:
        soft: 1048576
        hard: 1048576
    shm_size: '10gb'
    environment:
      - DYN_REQUEST_PLANE=tcp
      - HF_HOME=/data/hf
      - HF_HUB_CACHE=/data/hf/hub
    volumes:
      - ${HOME}/.cache/huggingface:/data/hf
    gpus: all
