name: dynamo_vllm_local_2

networks:
  server:
    driver: bridge

volumes:
  dynamo-file-kv:

services:
  dynamo-frontend:
    image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.1
    command: python3 -m dynamo.frontend --http-port 8000 --store-kv file
    networks:
      - server
    ports:
      - 8000:8000
    ulimits:
      memlock: -1
      stack: 67108864
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      - DYN_REQUEST_PLANE=tcp
      - HF_HOME=/data/hf
      - HF_HUB_CACHE=/data/hf/hub
      - DYN_FILE_KV=/data/dynamo_kv
    volumes:
      - ${HOME}/.cache/huggingface:/data/hf
      - ${HOME}/.cache/dynamo_kv:/data/dynamo_kv
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/live >/dev/null || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 10

  dynamo-vllm-backend:
    image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.8.1
    command: >
      python3 -m dynamo.vllm
      --model Qwen/Qwen3-32B-FP8
      --store-kv file
      --kv-events-config '{"enable_kv_cache_events": false}'
      --gpu-memory-utilization 0.8
      --max-model-len 10000
    networks:
      - server
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
      nofile:
        soft: 1048576
        hard: 1048576
    env_file:
      - ../.env
    environment:
      - DYN_REQUEST_PLANE=tcp
      - HF_HOME=/data/hf
      - HF_HUB_CACHE=/data/hf/hub
      - DYN_FILE_KV=/data/dynamo_kv
    volumes:
      - ${HOME}/.cache/huggingface:/data/hf
      - ${HOME}/.cache/dynamo_kv:/data/dynamo_kv
    gpus: all
    depends_on:
      dynamo-frontend:
        condition: service_healthy
